#!/bin/sh -e

export PATH="/usr/local/pony/bin:$PATH"

[ "$1" = "--version" ] && exec ponyc --version

cd /tmp

# Compile
cat - > code.pony
ponyc --verbose 0
rm code.pony

# Execute
shift
exec ./tmp "$@"
