env: { browser: true }

ignorePatterns: [ js/codemirror-legacy ]

parser: "@typescript-eslint/parser"

plugins: [ "@typescript-eslint" ]

parserOptions:
  ecmaFeatures: { jsx: true }
  ecmaVersion:  latest
  sourceType:   module

rules:
  array-bracket-newline:       [ error, consistent ]
  arrow-parens:                [ error, as-needed ]
  brace-style:                 [ error, stroustrup, { allowSingleLine: true } ]
  camelcase:                   [ error ]
  comma-dangle:                [ error, always-multiline ]
  indent:                      [ error ]
  keyword-spacing:             [ error ]
  no-trailing-spaces:          [ error ]
  no-unused-vars:              [ error, { varsIgnorePattern: ^createElement$ } ]
  no-var:                      [ error ]
  prefer-const:                [ error ]
  quote-props:                 [ error, consistent-as-needed ]
  quotes:                      [ error, single, { avoidEscape: true } ]
  semi:                        [ error, always, { omitLastInOneLineBlock: true } ]
  space-before-function-paren: [ error, { named: never } ]
