#!/bin/bash -e

user=-u`id -u`:`id -g`

# Assets - only re-run if assets.go is stale.
if (( $(stat -c %Y `ls -t assets/* | head -1`) > `stat -c %Y routes/assets.go` )); then
    docker pull alpine:edge
    docker build -t code-golf-assets assets
    docker run $user -v `pwd`:/work code-golf-assets
fi

# Code
docker pull debian:stretch
docker build -t code-golf .
dir=/root/go/src/github.com/jraspass/code-golf
docker run --rm $user -v `pwd`:$dir -w $dir code-golf
