#!/bin/bash -e

# Only re-run if assets.go is stale.
newest_file=$(ls -t assets/{,*/}* | head -1)
if [[ routes/assets.go -ot $newest_file ]]; then
    docker build --pull -t code-golf-assets assets
    docker run --rm -u $UID:$GROUPS -v $PWD:/work code-golf-assets
fi
