#!/bin/sh -e

docker pull alpine:edge

pwd=`pwd`

# Perl & Ruby
for lang in perl ruby; do
    cd $pwd/containers/$lang

    docker build -t $lang-build .

    id=`docker run -d $lang-build true`

    rm -fr rootfs
    mkdir -p rootfs/lib rootfs/usr/{bin,lib}

    docker cp $id:/lib/ld-musl-x86_64.so.1 rootfs/lib
    docker cp $id:/usr/bin/$lang           rootfs/usr/bin

    if [ $lang = 'perl' ]; then
        docker cp $id:/usr/lib/perl5 rootfs/usr/lib
    else
        docker cp $id:/usr/lib/$lang rootfs/usr/lib
    fi

    docker rm $id
done

# Cleanup
cd ..

sudo chown -R $USER: */rootfs

find */rootfs/usr/lib -regex '.*\.\(h\|md\|pod\)' -delete
