#!/bin/bash -e

docker pull alpine:edge

cd containers

for name in Bash Haskell JavaScript Lisp Lua Perl Perl\ 6 PHP Python Ruby; do
    lang=${name,,}      # lowercase
    lang=${lang// /}    # trim space

    # Start with a clean rootfs.
    rm -rf $lang/rootfs
    mkdir $lang/rootfs

    # Tag the builder stage so "docker system prune" won't remove it.
    if [ $lang != haskell -a $lang != j ]; then
        docker build --target builder -t code-golf-$lang-builder $lang
    fi

    docker build -t code-golf-$lang $lang

    ver=`docker run --rm code-golf-$lang`

    # Remove some crap from version strings.
    ver=${ver#Lua }
    ver=${ver#The Glorious }
    ver=${ver#This is }
    ver=${ver#JavaScript-C}
    ver=${ver/ation/er}
    ver=${ver/built /}
    ver=${ver/System, /}
    ver=${ver//$'\n'/ }
    ver=${ver//version /}
    ver=${ver%.}
    ver=${ver% d8> }
    ver=${ver%  Copyright (C) 1994-2018 Lua.org, PUC-Rio}
    ver=${ver/ (*/}

    html+="<tr><th>$name<td>$ver"

    id=`docker run -d code-golf-$lang`

    docker export $id | tar -C $lang/rootfs -xf -

    docker rm -f $id

    # Remove the crap we gained from running the container, this is hacky.
    rm -fr $lang/rootfs/{.dockerenv,dev,etc,proc,sys,tmp}

    mkdir $lang/rootfs/{old-root,proc,tmp}

    # Lisp & Python need UIDs to actually resolve, madness!
    if [ $lang = lisp -o $lang = python ]; then
        mkdir $lang/rootfs/etc

        echo nobody:x:99:99::/: > $lang/rootfs/etc/passwd
    fi
done

echo "package routes

const versionTable = \"$html\"" > ../routes/versions.go
