#!/bin/sh -e

rsync -achPe 'ssh -p 1988' --delete                \
    app code-golf.service containers run-container \
    code-golf.io:code-golf

ssh -p 1988 code-golf.io \
    'sudo systemctl daemon-reload && sudo systemctl restart code-golf'
