#!/bin/sh -e

./build-assets

docker build --pull -t code-golf .
docker run --rm -u $UID:$GROUPS -v $PWD:/go code-golf

rsync -achPe 'ssh -p 1988' --delete                       \
    code-golf code-golf.service holes.toml run-lang views \
    code-golf.io:code-golf

ssh -p 1988 code-golf.io \
    'sudo systemctl daemon-reload && sudo systemctl restart code-golf'
