#!/bin/sh -e

rm -rf dist esbuild.json

npm install

node_modules/.bin/esbuild "$@"        \
    --asset-names=[dir]/[name]-[hash] \
    --bundle                          \
    --entry-names=[dir]/[name]-[hash] \
    --format=esm                      \
    --inject:js/_inject.ts            \
    --jsx-factory=createElement       \
    --loader:.woff2=file              \
    --loader:.png=dataurl             \
    --metafile=esbuild.json           \
    --minify                          \
    --outbase=.                       \
    --outdir=dist                     \
    --public-path=/dist               \
    --sourcemap                       \
    --target=es2020                   \
    `find \
        css/font.css \
        node_modules/golden-layout/dist/css/themes/goldenlayout-light-theme.css \
        js \
        -type f \
        -not -name '_*'`
