#!/bin/sh -e

# Check for version
if [ "$1" = "--version" ]; then
    /usr/bin/swipl --version
    exit 0
fi

# Put user-defined predicates in file
cd /tmp
cat - > code.pl

# Ensure interpreter never shows its face in the output box.
# Concatenate 'halt' as a goal to every program.

swipl --quiet --on-error=halt -g 'halt.' code.pl "$@"
