#!/bin/sh -e

export LC_ALL=C.UTF-8

[ "$1" = "--version" ] && exec swipl --version

# Put user-defined predicates in file
cd /tmp
cat - > code.pl

# Ensure interpreter never shows its face in the output box.
# Concatenate 'halt' as a goal to every program.

swipl --quiet --on-error=halt -g halt. code.pl "$@"
