#!/bin/sh -e

[ "$1" = "-V" ] && exec cfunge -V

cd /tmp

cat - > code

shift
for arg in "$@"; do
    # Write NULL terminated argument to .txt file
    echo -ne "$arg\0" >> argv.txt
done

# Read arguments from .txt file
exec cfunge -bEW code < argv.txt
