#!/bin/sh -e

# Dummy input file shows version
[ "$1" = "" ] && exec bef foo.bf

cd /tmp

cat > code.bf

for arg in "$@"; do
    # Write argument to .txt file
    echo "$arg" >> argv.txt
done

# Pass arguments as .txt file
exec bef -q -r argv.txt code.bf
