#!/bin/bash -e

[ "$1" = "--version" ] && exec /opt/jdk/bin/java --version

export LC_ALL=C.UTF-8

cd /tmp

# Compile
cat - > code.java
/opt/jdk/bin/javac code.java
rm code.java

# Execute
shift
shopt -s nullglob
printf -v class %s *.class
exec /opt/jdk/bin/java "${class/.class*/}" "$@"
