openapi: 3.0.3

info:
  title: Code Golf API
  description: API for [Code Golf](https://code.golf).
  version: unstable

servers:
  - url: https://code.golf/api

paths:
  /cheevos:
    get:
      tags: [achievements]
      summary: Get all achievements
      responses:
        '200':
          description: A list of achievements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Achievement'

  /cheevos/{id}:
    get:
      parameters:
        - name: id
          description: Achievement ID
          in: path
          required: true
          schema:
            type: string
      tags: [achievements]
      summary: Get a achievements by ID
      responses:
        '200':
          description: A single achievement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Achievement'

  /holes:
    get:
      tags: [holes]
      summary: Get all holes
      responses:
        '200':
          description: A list of holes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hole'

  /holes/{id}:
    get:
      parameters:
        - name: id
          description: Hole ID
          in: path
          required: true
          schema:
            type: string
      tags: [holes]
      summary: Get a hole by ID
      responses:
        '200':
          description: A single hole
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hole'

  /langs:
    get:
      tags: [languages]
      summary: Get all languages
      responses:
        '200':
          description: A list of languages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Language'

  /langs/{id}:
    get:
      parameters:
        - name: id
          description: Language ID
          in: path
          required: true
          schema:
            type: string
      tags: [languages]
      summary: Get a language by ID
      responses:
        '200':
          description: A single language
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Language'

  /suggestions/golfers:
    get:
      parameters:
        - name: q
          description: Case-insensitive substring to search for
          in: query
          schema:
            type: string
      tags: [suggestions]
      summary: Returns a list of matching golfers, limited to 10
      responses:
        '200':
          description: A JSON array matching golfer names, limited to 10
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    Achievement:
      type: object
      properties:
        description:
          type: string
        emoji:
          type: string
        id:
          type: string
        name:
          type: string

    Hole:
      type: object
      properties:
        category:
          type: string
          enum: [Art, Computing, Gaming, Mathematics, Sequence, Transform]
        id:
          type: string
        links:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
                format: uri
        name:
          type: string
        preamble:
          type: string

    Language:
      type: object
      properties:
        example:
          type: string
        id:
          type: string
        name:
          type: string
        size:
          type: string
        version:
          type: string
        website:
          type: string
          format: uri
