version: '2'
services:
  app:
    command:
      - go
      - run
      - -tags
      - dev
      - .
    environment:
      E2E: 1
  db:
    tmpfs: /var/lib/postgresql/data
  e2e:
    depends_on:
      - app
      - db
      - firefox
    entrypoint:
      - prove6
      - -vIt
    environment:
      PGDATABASE: code-golf
      PGHOST:     db
      PGSSLMODE:  disable
      PGUSER:     postgres
    image: jraspass/raku:toolbox
    tty: true
    volumes:
      - ..:/code-golf
    working_dir: /code-golf
  firefox:
    build:
      context: .
      dockerfile: firefox.Dockerfile
