#!/bin/sh -e

[ "$1" = "version" ] && exec /usr/local/go/bin/go version

# Compile
# Separate compile and link relies on environment variables less than "go run"
# does. "go run" also doesn't support reading the file from stdin.
cat - > /tmp/code.go
/usr/local/go/bin/go tool compile -o /tmp/code.o /tmp/code.go 1>&2
/usr/local/go/bin/go tool link    -o /tmp/code   /tmp/code.o  1>&2
rm /tmp/code.go /tmp/code.o

# Execute
shift
exec /tmp/code "$@"
