#!/bin/sh -e

[ "$1" = "--version" ] && exec go version

cd /tmp

# Copy the cache to /tmp so it's mutable, this is hacky but faster than
# running Go without the stdlib cached.
cp -r /cache .cache

# Compile
cat - > code.go
go build code.go
rm code.go

# Execute
shift
exec ./code "$@"
