#!/bin/sh -e

cd /tmp

if [ "$1" = "--version" ]; then
  # Write version to .dyalog file
  echo "⎕←2⊃⎕WG'APLVersion'" > code.dyalog
else
  cat - > code.dyalog
  shift
fi

# Execute
exec dyalogscript code.dyalog "$@"
