#!/bin/sh -e

[ "$1" = "--version" ] && exec gp --version-short

cd /tmp

cat - > code.gp
touch input.txt

shift
for arg in "$@"; do
    # Write argument to .txt file
    echo "$arg" >> input.txt
done

# Execute
exec gp --fast --quiet code.gp
