#!/bin/sh -e

[ "$1" = "--version" ] && exec gp --version-short

cd /tmp

touch ARGV
cat - > code.gp

shift
for arg in "$@"; do
    # Write argument to `ARGV`
    echo "$arg" >> ARGV
done

# Execute
exec gp --fast --quiet code.gp
