Africa = [
    { id = 'DZ', name = 'Algeria' },
    { id = 'AO', name = 'Angola' },
    { id = 'BJ', name = 'Benin' },
    { id = 'BW', name = 'Botswana' },
    { id = 'BF', name = 'Burkina Faso' },
    { id = 'BI', name = 'Burundi' },
    { id = 'CM', name = 'Cameroon' },
    { id = 'IC', name = 'Canary Islands' },
    { id = 'CV', name = 'Cape Verde' },
    { id = 'CF', name = 'Central African Republic' },
    { id = 'EA', name = 'Ceuta and Melilla' },
    { id = 'TD', name = 'Chad' },
    { id = 'KM', name = 'Comoros' },
    { id = 'CD', name = 'Democratic Republic of the Congo' },
    { id = 'DJ', name = 'Djibouti' },
    { id = 'EG', name = 'Egypt' },
    { id = 'GQ', name = 'Equatorial Guinea' },
    { id = 'ER', name = 'Eritrea' },
    { id = 'SZ', name = 'Eswatini' },
    { id = 'ET', name = 'Ethiopia' },
    { id = 'TF', name = 'French Southern Territories' },
    { id = 'GA', name = 'Gabon' },
    { id = 'GM', name = 'The Gambia' },
    { id = 'GH', name = 'Ghana' },
    { id = 'GN', name = 'Guinea' },
    { id = 'GW', name = 'Guinea-Bissau' },
    { id = 'CI', name = 'Ivory Coast' },
    { id = 'KE', name = 'Kenya' },
    { id = 'LS', name = 'Lesotho' },
    { id = 'LR', name = 'Liberia' },
    { id = 'LY', name = 'Libya' },
    { id = 'MG', name = 'Madagascar' },
    { id = 'MW', name = 'Malawi' },
    { id = 'ML', name = 'Mali' },
    { id = 'MR', name = 'Mauritania' },
    { id = 'MU', name = 'Mauritius' },
    { id = 'YT', name = 'Mayotte' },
    { id = 'MA', name = 'Morocco' },
    { id = 'MZ', name = 'Mozambique' },
    { id = 'NA', name = 'Namibia' },
    { id = 'NE', name = 'Niger' },
    { id = 'NG', name = 'Nigeria' },
    { id = 'CG', name = 'Republic of the Congo' },
    { id = 'RE', name = 'Réunion' },
    { id = 'RW', name = 'Rwanda' },
    { id = 'SH', name = 'Saint Helena, Ascension and Tristan da Cunha' },
    { id = 'ST', name = 'São Tomé and Príncipe' },
    { id = 'SN', name = 'Senegal' },
    { id = 'SC', name = 'Seychelles' },
    { id = 'SL', name = 'Sierra Leone' },
    { id = 'SO', name = 'Somalia' },
    { id = 'ZA', name = 'South Africa' },
    { id = 'SS', name = 'South Sudan' },
    { id = 'SD', name = 'Sudan' },
    { id = 'TZ', name = 'Tanzania' },
    { id = 'TG', name = 'Togo' },
    { id = 'TN', name = 'Tunisia' },
    { id = 'UG', name = 'Uganda' },
    { id = 'EH', name = 'Western Sahara' },
    { id = 'ZM', name = 'Zambia' },
    { id = 'ZW', name = 'Zimbabwe' },
]

Asia = [
    { id = 'AF', name = 'Afghanistan' },
    { id = 'BH', name = 'Bahrain' },
    { id = 'BD', name = 'Bangladesh' },
    { id = 'BT', name = 'Bhutan' },
    { id = 'BN', name = 'Brunei' },
    { id = 'KH', name = 'Cambodia' },
    { id = 'CN', name = 'China' },
    { id = 'CY', name = 'Cyprus' },
    { id = 'HK', name = 'Hong Kong' },
    { id = 'IN', name = 'India' },
    { id = 'ID', name = 'Indonesia' },
    { id = 'IR', name = 'Iran' },
    { id = 'IQ', name = 'Iraq' },
    { id = 'IL', name = 'Israel' },
    { id = 'JP', name = 'Japan' },
    { id = 'JO', name = 'Jordan' },
    { id = 'KZ', name = 'Kazakhstan' },
    { id = 'KW', name = 'Kuwait' },
    { id = 'KG', name = 'Kyrgyzstan' },
    { id = 'LA', name = 'Laos' },
    { id = 'LB', name = 'Lebanon' },
    { id = 'MY', name = 'Malaysia' },
    { id = 'MV', name = 'Maldives' },
    { id = 'MN', name = 'Mongolia' },
    { id = 'MM', name = 'Myanmar' },
    { id = 'NP', name = 'Nepal' },
    { id = 'KP', name = 'North Korea' },
    { id = 'OM', name = 'Oman' },
    { id = 'PK', name = 'Pakistan' },
    { id = 'PS', name = 'Palestine' },
    { id = 'PH', name = 'Philippines' },
    { id = 'QA', name = 'Qatar' },
    { id = 'SA', name = 'Saudi Arabia' },
    { id = 'SG', name = 'Singapore' },
    { id = 'KR', name = 'South Korea' },
    { id = 'LK', name = 'Sri Lanka' },
    { id = 'SY', name = 'Syria' },
    { id = 'TW', name = 'Taiwan' },
    { id = 'TJ', name = 'Tajikistan' },
    { id = 'TH', name = 'Thailand' },
    { id = 'TL', name = 'Timor-Leste' },
    { id = 'TR', name = 'Turkey' },
    { id = 'TM', name = 'Turkmenistan' },
    { id = 'AE', name = 'United Arab Emirates' },
    { id = 'UZ', name = 'Uzbekistan' },
    { id = 'VN', name = 'Vietnam' },
    { id = 'YE', name = 'Yemen' },
]

Europe = [
    { id = 'AX', name = 'Åland Islands' },
    { id = 'AL', name = 'Albania' },
    { id = 'AD', name = 'Andorra' },
    { id = 'AM', name = 'Armenia' },
    { id = 'AT', name = 'Austria' },
    { id = 'AZ', name = 'Azerbaijan' },
    { id = 'BY', name = 'Belarus' },
    { id = 'BE', name = 'Belgium' },
    { id = 'BA', name = 'Bosnia and Herzegovina' },
    { id = 'BG', name = 'Bulgaria' },
    { id = 'HR', name = 'Croatia' },
    { id = 'CY', name = 'Cyprus' },
    { id = 'CZ', name = 'Czech Republic' },
    { id = 'DK', name = 'Denmark' },
    { id = 'EE', name = 'Estonia' },
    { id = 'FO', name = 'Faroe Islands' },
    { id = 'FI', name = 'Finland' },
    { id = 'FR', name = 'France' },
    { id = 'GE', name = 'Georgia' },
    { id = 'DE', name = 'Germany' },
    { id = 'GI', name = 'Gibraltar' },
    { id = 'GR', name = 'Greece' },
    { id = 'GL', name = 'Greenland' },
    { id = 'GG', name = 'Guernsey' },
    { id = 'HU', name = 'Hungary' },
    { id = 'IS', name = 'Iceland' },
    { id = 'IE', name = 'Ireland' },
    { id = 'IM', name = 'Isle of Man' },
    { id = 'IT', name = 'Italy' },
    { id = 'JE', name = 'Jersey' },
    { id = 'KZ', name = 'Kazakhstan' },
    { id = 'XK', name = 'Kosovo' },
    { id = 'LV', name = 'Latvia' },
    { id = 'LI', name = 'Liechtenstein' },
    { id = 'LT', name = 'Lithuania' },
    { id = 'LU', name = 'Luxembourg' },
    { id = 'MT', name = 'Malta' },
    { id = 'MD', name = 'Moldova' },
    { id = 'MC', name = 'Monaco' },
    { id = 'ME', name = 'Montenegro' },
    { id = 'NL', name = 'Netherlands' },
    { id = 'MK', name = 'North Macedonia' },
    { id = 'NO', name = 'Norway' },
    { id = 'PL', name = 'Poland' },
    { id = 'PT', name = 'Portugal' },
    { id = 'RO', name = 'Romania' },
    { id = 'RU', name = 'Russia' },
    { id = 'SM', name = 'San Marino' },
    { id = 'RS', name = 'Serbia' },
    { id = 'SK', name = 'Slovakia' },
    { id = 'SI', name = 'Slovenia' },
    { id = 'ES', name = 'Spain' },
    { id = 'SJ', name = 'Svalbard' },
    { id = 'SE', name = 'Sweden' },
    { id = 'CH', name = 'Switzerland' },
    { id = 'UA', name = 'Ukraine' },
    { id = 'GB', name = 'United Kingdom' },
    { id = 'VA', name = 'Vatican City' },
]

'North America' = [
    { id = 'AI', name = 'Anguilla' },
    { id = 'AG', name = 'Antigua and Barbuda' },
    { id = 'AW', name = 'Aruba' },
    { id = 'BS', name = 'Bahamas' },
    { id = 'BB', name = 'Barbados' },
    { id = 'BZ', name = 'Belize' },
    { id = 'BM', name = 'Bermuda' },
    { id = 'VG', name = 'British Virgin Islands' },
    { id = 'CA', name = 'Canada' },
    { id = 'BQ', name = 'Caribbean Netherlands' },
    { id = 'KY', name = 'Cayman Islands' },
    { id = 'CP', name = 'Clipperton Island' },
    { id = 'CR', name = 'Costa Rica' },
    { id = 'CU', name = 'Cuba' },
    { id = 'CW', name = 'Curaçao' },
    { id = 'DM', name = 'Dominica' },
    { id = 'DO', name = 'Dominican Republic' },
    { id = 'SV', name = 'El Salvador' },
    { id = 'GD', name = 'Grenada' },
    { id = 'GP', name = 'Guadeloupe' },
    { id = 'GT', name = 'Guatemala' },
    { id = 'HT', name = 'Haiti' },
    { id = 'HN', name = 'Honduras' },
    { id = 'JM', name = 'Jamaica' },
    { id = 'MQ', name = 'Martinique' },
    { id = 'MX', name = 'Mexico' },
    { id = 'MS', name = 'Montserrat' },
    { id = 'NI', name = 'Nicaragua' },
    { id = 'PA', name = 'Panama' },
    { id = 'PR', name = 'Puerto Rico' },
    { id = 'BL', name = 'Saint Barthélemy' },
    { id = 'KN', name = 'Saint Kitts and Nevis' },
    { id = 'LC', name = 'Saint Lucia' },
    { id = 'MF', name = 'Saint Martin' },
    { id = 'PM', name = 'Saint Pierre and Miquelon' },
    { id = 'VC', name = 'Saint Vincent and the Grenadines' },
    { id = 'SX', name = 'Sint Maarten' },
    { id = 'TT', name = 'Trinidad and Tobago' },
    { id = 'TC', name = 'Turks and Caicos Islands' },
    { id = 'US', name = 'United States' },
    { id = 'VI', name = 'United States Virgin Islands' },
]

Oceania = [
    { id = 'AS', name = 'American Samoa' },
    { id = 'AU', name = 'Australia' },
    { id = 'CX', name = 'Christmas Island' },
    { id = 'CC', name = 'Cocos (Keeling) Islands' },
    { id = 'CK', name = 'Cook Islands' },
    { id = 'FM', name = 'Federated States of Micronesia' },
    { id = 'FJ', name = 'Fiji' },
    { id = 'PF', name = 'French Polynesia' },
    { id = 'GU', name = 'Guam' },
    { id = 'KI', name = 'Kiribati' },
    { id = 'MH', name = 'Marshall Islands' },
    { id = 'NR', name = 'Nauru' },
    { id = 'NC', name = 'New Caledonia' },
    { id = 'NZ', name = 'New Zealand' },
    { id = 'NU', name = 'Niue' },
    { id = 'NF', name = 'Norfolk Island' },
    { id = 'PW', name = 'Palau' },
    { id = 'PG', name = 'Papua New Guinea' },
    { id = 'PN', name = 'Pitcairn Islands' },
    { id = 'WS', name = 'Samoa' },
    { id = 'SB', name = 'Solomon Islands' },
    { id = 'TK', name = 'Tokelau' },
    { id = 'TO', name = 'Tonga' },
    { id = 'TV', name = 'Tuvalu' },
    { id = 'VU', name = 'Vanuatu' },
    { id = 'WF', name = 'Wallis and Futuna' },
]

'South America' = [
    { id = 'AR', name = 'Argentina' },
    { id = 'BO', name = 'Bolivia' },
    { id = 'BV', name = 'Bouvet Island' },
    { id = 'BR', name = 'Brazil' },
    { id = 'CL', name = 'Chile' },
    { id = 'CO', name = 'Colombia' },
    { id = 'EC', name = 'Ecuador' },
    { id = 'FK', name = 'Falkland Islands' },
    { id = 'GF', name = 'French Guiana' },
    { id = 'GY', name = 'Guyana' },
    { id = 'PY', name = 'Paraguay' },
    { id = 'PE', name = 'Peru' },
    { id = 'GS', name = 'South Georgia and the South Sandwich Islands' },
    { id = 'SR', name = 'Suriname' },
    { id = 'UY', name = 'Uruguay' },
    { id = 'VE', name = 'Venezuela' },
]
