#!/bin/sh -e

cd /tmp

cat - > code.txt

shift
touch argv.txt
for arg in "$@"; do
    # Write NULL terminated argument to .txt file
    echo -ne "$arg\0" >> argv.txt
done

# Encode ASCII to PNG
piet code.txt > code.png

# Decode PNG and read arguments from .txt file
exec npiet -v11 code.png < argv.txt
