#!/bin/sh -e

cd /tmp

cat - > code.txt

shift
touch argv.txt
for arg in "$@"; do
    # Write argument to .txt file
    echo "$arg" >> argv.txt
done

# Encode ASCII to Portable Pixmap
piet code.txt > code.ppm

# Decode PPM and read arguments from .txt file
exec npiet -v11 code.ppm < argv.txt
