#!/bin/sh -e

mkdir -p assets/out
find assets/out -type f ! -name .gitignore -delete

npm install

node_modules/.bin/esbuild "$@"            \
    --asset-names=[dir]/[name]-[hash]     \
    --bundle                              \
    --entry-names=[dir]/[name]-[hash]     \
    --format=esm                          \
    --inject:assets/js/_inject.ts         \
    --jsx-factory=createElement           \
    --loader:.svg=copy                    \
    --loader:.woff2=file                  \
    --metafile=assets/out/meta.json       \
    --minify                              \
    --outbase=assets                      \
    --outdir=assets/out                   \
    --public-path=/assets                 \
    --sourcemap                           \
    --target=es2020,chrome88              \
    `find assets/css assets/js assets/svg \
        -type f -not -name '_*' -not -path '*/vendor/*'`
