#!/bin/sh -e

cd /tmp

cat - > code.abe

shift
touch argv.txt
for arg in "$@"; do
    # Write argument to .txt file
    echo -e "$arg" >> argv.txt
done

# Execute and read arguments from .txt file
exec python /osabie/osabie.py code.abe < argv.txt
