#!/bin/sh -e

export PATH=/usr/bin:/bin

[ "$1" = "-v" ] && exec rocky

cd /tmp

shift

# Since \" isn't supported, use a variable to escape quotes.
echo "cast 34 into quote" >> code.rock

echo 'rock args' >> code.rock

# Inject args variable into code
while [[ $# -gt 0 ]]; do

  # Escape backslashes, newlines, and quotes
  escaped="$(\
    printf '%s' "$1" \
      | sed -e 's/\\/\\\\/g' \
      | sed -e 's/"/"+quote+"/g' \
      | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g' \
  )"

  printf 'rock "%s" into args\n' "$escaped" >> code.rock

  shift
done

# Unset variables
echo "let quote be mysterious" >> code.rock

# Write code to .rock file
cat - >> code.rock

# Execute
exec rocky run --infinite-loops --rocky code.rock
