#!/bin/sh -e

export JAVA_HOME=/usr/lib/jre
export PATH=/usr/lib/jre/bin:$PATH

[ "$1" = "-version" ] && exec /usr/local/bin/scala -version

cat - > /tmp/code.scala

shift
exec /usr/local/bin/scala /tmp/code.scala "$@"
