#!/bin/sh -e

[ "$1" = "--version" ] && exec curry --version

cd /tmp

# Compile
cat - > code.curry
curry -Dbindingoptimization=no --nocypm --quiet :load code.curry :save :quit
rm code.curry

# Execute
shift
exec ./code "$@"
