#!/bin/bash -e

if [ "$1" = "-v" ]
then
  /usr/local/bin/tex -v
  exit
fi

function join_by {
  # https://stackoverflow.com/a/17841619/7481517
  local sep=${1-} f=${2-}
  if shift 2; then
    printf %s "$f" "${@/#/$sep}"
  fi
}

cd /tmp

code="$1"
shift

args=$(join_by "\or " "$@")
init="\def\argc{$#} \def\argv[#1]{\ifcase#1\relax $args\else\fi}"

# \footline={} disables page numbers
# \parindex=0pt prevents per-paragraph indentation
# \hsize and \vsize set the page dimensions. I set them a bit less than the
#   maximum legal dimension which is less than 16384pt.
# \bye closes the document (TeX doesn't handle EOF how you might expect)
code_to_run="\footline={}\parindent=0pt\hsize=16000pt\vsize=16000pt\relax
$init
$code
\bye"

echo "$code_to_run" | /usr/local/bin/tex >&2

dvi-to-text texput.dvi

echo "-----------" >&2

cat texput.log >&2
