#!/bin/bash -e

if [ "$1" = "-v" ]
then
  /usr/local/bin/tex -v
  exit
fi

function join_by {
  # https://stackoverflow.com/a/17841619/7481517
  local sep=${1-} f=${2-}
  if shift 2; then
    printf %s "$f" "${@/#/$sep}"
  fi
}

cd /tmp

code="$1"
shift

# To pass in values, we need to escape some special characters
# All the special characters \{}%&#^_%~ are set to catcode 12 ("other")
# Also set the whitespace characters to catcode 12, unlike \dospecials
# But we still need access to some to finish the definition, so we use
#   byte 1 = begin group (previously {)
#   byte 2 = end group (previously })
#   byte 4 = space
#   byte 5 = escape (previously \)
#   byte 6 = parameter (previously #)
# The end of the group resets all the catcodes for future tokenizing, but it
# does not change the catcodes of the tokens already created
args=$(join_by "or" "$@")
init="\def\argc{$#}
"'{\catcode1=1\catcode2=2\catcode5=0\catcode6=6\catcode4=10
\catcode`$=12\catcode`&=12\catcode`^=12\catcode`_=12\catcode37=12
\catcode`~=12\catcode`#=12\catcode`{=12\catcode`}=12\catcode9=12
\catcode32=12\catcode10=12\catcode12=12\catcode13=13\catcode92=12
globaldefargv[1]ifcase1'"$args"'elsefi'

# \octet enables the octet font
# \footline={} disables page numbers
# \parindex=0pt prevents per-paragraph indentation
# \hsize and \vsize set the page dimensions. I set them a bit less than the
#   maximum legal dimension which is less than 16384pt.
# \bye closes the document (TeX doesn't handle EOF how you might expect)
code_to_run="\octet\footline={}\parindent=0pt\hsize=16000pt\vsize=16000pt\relax
$init
$code
\bye"

# don't stop the bash script if /usr/local/bin/tex errors
set +e

# The randoms might not actually prevent reading the file, but they do
# certainly help avoid grepping out the wrong line
FILENAME="solution_${RANDOM}_${RANDOM}_${RANDOM}_${RANDOM}"

echo "$code_to_run" > "$FILENAME.tex"

/usr/local/bin/tex "$FILENAME.tex" >/dev/null

cat "$FILENAME.log" \
  | grep -Fv "$FILENAME." \
  | grep -Fv "This is TeX, Version 3.141592653" \
  | grep -Fv " [1] )" \
  >&2

if [[ -f "$FILENAME.dvi" ]]; then
  dvi-to-text "$FILENAME.dvi"
fi
