#!/bin/bash -e

if [ "$1" = "-v" ]
then
  /bin/tex -v
  exit
fi

function join_by {
  # https://stackoverflow.com/a/17841619/7481517
  local sep=${1-} f=${2-}
  if shift 2; then
    printf %s "$f" "${@/#/$sep}"
  fi
}

cd /tmp

code="$1"
shift

args=$(join_by "\or " "$@")
init="\def\argc{$#} \def\argv[#1]{\ifcase#1\relax $args\else\fi}"

# \footline={} disables page numbers
# \end marks the end of the document (TeX ignores stdin EOF)
#   \bye is preferred over \end, but it's not strictly necessary, so I went with
#   \end to close out the file instead of \bye
code_to_run="\footline={}
$init
$code
\end"

echo "$code_to_run" | /bin/tex >/dev/null

dvi-to-text texput.dvi

cat texput.log >&2
