#!/bin/sh -e

[ "$1" = "--version" ] && exec nibbles -v

cd /tmp

cp -R /usr/local/bin/* .

cat - > code.nbl

shift
touch argv.txt
for arg in "$@"; do
    # Write argument to .txt file
    echo "$arg" >> argv.txt
done

# Execute and read arguments from .txt file
exec nibbles code.nbl < argv.txt 2>&1 | grep -v " nibbles "

# IN PROGRESS: This eliminates that default message but displays just everything on stdout :pleading_face:
