#!/bin/sh -e

[ "$1" = "version" ] && exec /usr/local/bin/zig version

cd /tmp

# Compile
cat - > code.zig
/usr/local/bin/zig build-exe --global-cache-dir . -fstrip -freference-trace --color on code.zig
rm code.zig

# Execute
shift
exec ./code "$@"
