#!/bin/sh -e

if [ "$1" = "version" ]; then
    /usr/local/bin/zig version
    exit 0
fi

cd /tmp

# Compile
cat - > code.zig
/usr/local/bin/zig build-exe --global-cache-dir . --strip code.zig
rm code.zig

# Execute
shift
exec ./code "$@"
