#!/bin/sh -e

export CARGO_HOME=/usr/local/cargo
export PATH=/usr/local/cargo/bin:$PATH
export RUSTUP_HOME=/usr/local/rustup
export RUST_BACKTRACE=1

[ "$1" = "--version" ] && exec rustc --version

# Compile
rustc --edition 2021 -C linker=ld -C opt-level=2 -o /tmp/code --color always -

# Execute
shift
exec /tmp/code "$@"
