#!/bin/sh -e

if [ "$1" = "--version" ]; then
    /usr/local/cargo/bin/rustc --version
    exit 0
fi

export CARGO_HOME=/usr/local/cargo
export RUST_BACKTRACE=1
export RUSTUP_HOME=/usr/local/rustup
export PATH=/usr/local/cargo/bin:$PATH

# Compile
rustc -o /tmp/code -

# Execute
shift
exec /tmp/code "$@"
